 const ADD_LOADER = "ADD_LOADER";
 const REMOVE_LOADER = "REMOVE_LOADER";
 const GET_ERRORS = "GET_ERRORS";
 const CLEAR_ERRORS= "CLEAR_ERRORS";
 const GET_NOTIFICATION= "GET_NOTIFICATION"
 const CLEAR_NOTIFICATION= "CLEAR_NOTIFICATION"

export {ADD_LOADER, REMOVE_LOADER, GET_ERRORS, CLEAR_ERRORS,GET_NOTIFICATION,CLEAR_NOTIFICATION}
